# Generated by Django 3.2.15 on 2023-05-27 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('description', models.CharField(blank=True, max_length=1023)),
                ('weight', models.IntegerField()),
                ('repetitions', models.SmallIntegerField(default=3)),
                ('series', models.SmallIntegerField(default=3)),
                ('trainingday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trainingday')),
            ],
        ),
    ]
