# Generated by Django 3.2.15 on 2023-05-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingexercise',
            old_name='trainingday',
            new_name='training_day',
        ),
        migrations.AlterField(
            model_name='trainingexercise',
            name='description',
            field=models.TextField(blank=True, max_length=1023),
        ),
    ]
