# Generated by Django 3.2.15 on 2023-05-29 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230527_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('description', models.TextField(blank=True, max_length=1023)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('repetitions', models.SmallIntegerField(default=3)),
                ('series', models.SmallIntegerField(default=3)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
            ],
        ),
        migrations.DeleteModel(
            name='TrainingExercise',
        ),
        migrations.AddField(
            model_name='trainingday',
            name='exercises',
            field=models.ManyToManyField(to='core.ExerciseConfig'),
        ),
        migrations.AddField(
            model_name='trainingday',
            name='plan',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.plan'),
            preserve_default=False,
        ),
    ]
