# Generated by Django 3.2.15 on 2023-05-30 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230529_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('exerciseconfig_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.exerciseconfig')),
            ],
            bases=('core.exerciseconfig',),
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='exerciseconfig',
            name='repetitions',
            field=models.SmallIntegerField(default=8),
        ),
        migrations.DeleteModel(
            name='TrainingDay',
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(related_name='_core_workout_exercises_+', to='core.ExerciseConfig'),
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workoutlog'),
        ),
        migrations.AddField(
            model_name='plan',
            name='workout_set',
            field=models.ManyToManyField(to='core.Workout'),
        ),
    ]
