# Generated by Django 3.2.15 on 2023-05-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230530_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(related_name='workouts', to='core.ExerciseConfig'),
        ),
    ]
