# Generated by Django 3.2.15 on 2023-06-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_workout_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='workout_set',
            field=models.ManyToManyField(related_name='plans', to='core.Workout'),
        ),
    ]
